// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImHawDiXiJdoWlTTNNX3g5jJV4duDyNQ',
    appId: '1:705246089595:web:34a84c4b0919ebb7f22dde',
    messagingSenderId: '705246089595',
    projectId: 'appsmoviles-firebaseauth',
    authDomain: 'appsmoviles-firebaseauth.firebaseapp.com',
    storageBucket: 'appsmoviles-firebaseauth.firebasestorage.app',
    measurementId: 'G-1MLM9BYRHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKlT2zwhGRM1UC_vr3_2IuZxrY_m90adA',
    appId: '1:705246089595:android:34302932c6e8440ff22dde',
    messagingSenderId: '705246089595',
    projectId: 'appsmoviles-firebaseauth',
    storageBucket: 'appsmoviles-firebaseauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDiwEWgT7MMZtDiwb1OTElomSZPcHXBpc',
    appId: '1:705246089595:ios:f1bbc12a03bc725df22dde',
    messagingSenderId: '705246089595',
    projectId: 'appsmoviles-firebaseauth',
    storageBucket: 'appsmoviles-firebaseauth.firebasestorage.app',
    iosClientId: '705246089595-h2aq99ere98kcjuspuia71038od315db.apps.googleusercontent.com',
    iosBundleId: 'com.example.caropshibrida',
  );
}
